### ISSUE TITLE
Daftar pemilih tetap (sub menu kependudukan)

### ISSUE THREAD

**Issue by lulus2019** [Sahrun/SID#11]
pada sub menu ini menampilkan daftar penduduk yang usianya **17 tahun ke atas saat pemilu dilaksanakan**
![daftar pemilih](https://user-images.githubusercontent.com/59117200/71390676-d2338200-2633-11ea-9db7-42b19ce27d84.png)

**Comment by lulus2019** [comment]
![dpt](https://user-images.githubusercontent.com/59117200/71569138-85eab500-2aff-11ea-8fc0-d9060ea87d5c.png)

**Comment by Sahrun** [comment]
Sudah
