### ISSUE TITLE
TAMBAH FITUR EXPORT DI SUBMENU PENDUDUK

### ISSUE THREAD

**Issue by lulus2019** [Sahrun/SID#16]
tambah fitur export pada view penduduk berbentuk excel.
menampilkan semua data..
![penduduk](https://user-images.githubusercontent.com/59117200/71392217-e8444100-2639-11ea-82ad-e76287f8a015.png)

**Comment by rzwibowo** [comment]
commit id 44e03b9[https://github.com/Sahrun/SID/commit/44e03b94f0ca69ee73356f574661d0df2d1bd31c]
