### ISSUE TITLE
Riz tolong buatkan Menu User utk login

### ISSUE THREAD

**Issue by lulus2019** [Sahrun/SID#20]
buat inputan user yang bisa membuat akun login, dengan role  admin dan staff.. dengan level admin bisa membuka semua tampilan menu, staff hanya bisa menampilkan kependudukan dan laporan..

**Comment by lulus2019** [comment]
dengan isian input
Nama
email
pilihan role admin/staff (dropdown)
password
rePassword

**Comment by rzwibowo** [comment]
untuk commit 34e8c52 jangan lupa impor data untuk tabel user_role dulu

**Comment by lulus2019** [comment]
![image](https://user-images.githubusercontent.com/59117200/71674436-be171f80-2dad-11ea-9615-e8f83248e3ae.png)
kok ngene riz?

**Comment by lulus2019** [comment]
oke, coba test

**Comment by lulus2019** [comment]
![image](https://user-images.githubusercontent.com/59117200/71674838-ebb09880-2dae-11ea-9068-df11f46006d0.png)
user sahrun level staff ya? nek masuk administrator piye riz?

**Comment by lulus2019** [comment]
solved riz.. tak ubah manual seko db

**Comment by lulus2019** [comment]
sekalian ning dasboard sing my profil karo setting ya riz.. thx

**Comment by rzwibowo** [comment]
Setting apa?

**Comment by lulus2019** [comment]
rasah riz, ben aku wae ko gampang..

**Comment by lulus2019** [comment]
close ya

**Comment by rzwibowo** [comment]
cek di commit b03c050
