### ISSUE TITLE
surat kurang mampu

### ISSUE THREAD

**Issue by lulus2019** [Sahrun/SID#27]
kurang form inputan untuk nomor surat
![form surat](https://user-images.githubusercontent.com/59117200/71571145-7b361d00-2b0b-11ea-8d6a-bae3444c9eb9.png)
![surat tidak mampu](https://user-images.githubusercontent.com/59117200/71571151-825d2b00-2b0b-11ea-9859-cc806fc3be39.png)

**Comment by Sahrun** [comment]
sudah
