### ISSUE TITLE
surat pengantar

### ISSUE THREAD

**Issue by lulus2019** [Sahrun/SID#28]
untuk form, hapus form input no nik, no kk, golongan darah. karena direct data dari penduduk yg dipilih..
![form surat pengantar](https://user-images.githubusercontent.com/59117200/71571447-dae0f800-2b0c-11ea-9622-7a59ee555952.png)

data no kk no nik gol darah diambil dari data yg dipilih di form inputan. untuk alamat masih dobel RT
![surat pengantar](https://user-images.githubusercontent.com/59117200/71571479-09f76980-2b0d-11ea-8459-ab9e8d0c5f5c.png)

**Comment by lulus2019** [comment]
drop down penduduk menampilkan semua penduduk kecuali yg statusnya mati dan pindah

**Comment by Sahrun** [comment]
sudah dikerjakan ,  RT Double karna nama RT-nya **RT 1**
