### ISSUE TITLE
surat penduduk pindah

### ISSUE THREAD

**Issue by lulus2019** [Sahrun/SID#29]
pengikut pindah kepala keluarga masih dobel, harusnya tidak memunculkan lagi pengikuut yg sudah input di dropdown penduduk, misal sahrun yg dipilih di dropdown penduduk, dia tdk akan muncul di pengikut

**Comment by lulus2019** [comment]
![pindah form](https://user-images.githubusercontent.com/59117200/71571716-3f508700-2b0e-11ea-9a5f-456aec43b7b9.png)

**Comment by Sahrun** [comment]
Seharusnya sudah benar
