### ISSUE TITLE
Laporan statistik, dan dashboard

### ISSUE THREAD

**Issue by lulus2019** [Sahrun/SID#31]
riz, data terupdate kok ga terupdate ning statistik kuwi salah db ku opo script e riz, wes tak update jumlah penduduk tambahi, data ttp kebaca satu orang tok, begitu jg jenis kelamin.. opo perlu dihapus kabeh sek db ne nggonku?

**Comment by rzwibowo** [comment]
cobo ndelok datane sing mbok insert kan, jangan2 ra sesuai dengan filter (penduduk status bukan meninggal atau pindah)

**Comment by lulus2019** [comment]
![statistik](https://user-images.githubusercontent.com/59117200/71667143-599c9600-2d96-11ea-8f6a-be082e5cf5f5.png)
Data ada dua penduduk, status tetap dan lahir

![dasboard](https://user-images.githubusercontent.com/59117200/71667187-8c468e80-2d96-11ea-81b0-1ae679c1893c.png)
di dashboard dan lap statistik yg terdata cuma satu, dan wilayah jg ada dua dusun tapi yg masuk cuma satu dusun, dan satu dusun cuma ada satu orang, padahal ada 2 org di dusun 1 dan dusun 2 mmg kosong..

**Comment by lulus2019** [comment]
pada statistik ada satu dusun yg terbaca, atasnya malah ada 7 dusun, dan pada nyatanya hanya ada 2 dusun 
![image](https://user-images.githubusercontent.com/59117200/71667387-7ab1b680-2d97-11ea-93a9-c252a8901fac.png)

**Comment by lulus2019** [comment]
data jumlah rw dan jumlah rt blm sinkron

**Comment by lulus2019** [comment]
begitu juga statistik dusun di dasboard

**Comment by lulus2019** [comment]
dan di lap statistik jg blm mau sinkron dengan data penduduk yg ada

**Comment by lulus2019** [comment]
sory, solved riz sing nduwur, tinggal edit user ya

**Comment by lulus2019** [comment]
karo hapus

**Comment by rzwibowo** [comment]
lah salah close berarti
