### ISSUE TITLE
Form Input Pekerjaan

### ISSUE THREAD

**Issue by lulus2019** [Sahrun/SID#35]
form pekerjaan yang tandinya inputan, diganti dropdown..
kriteria pekerjaan

- 'BELUM/TIDAK BEKERJA'
- 'MENGURUS RUMAH TANGGA'
- 'PELAJAR/MAHASISWA'
- 'PENSIUNAN'
- 'PEGAWAI NEGERI SIPIL (PNS)'
- 'TENTARA NASIONAL INDONESIA (TNI)'
- 'KEPOLISIAN RI (POLRI)'
- 'PERDAGANGAN'
- 'PETANI/PEKEBUN'
- 'KARYAWAN SWASTA'
- 'KARYAWAN HONORER'
- 'BURUH HARIAN LEPAS'
- 'PEMBANTU RUMAH TANGGA'
- 'SENIMAN'
- 'GURU'
-  'KONSULTAN'
- 'DOKTER'
- 'PERANGKAT DESA'
- 'WIRASWASTA'
- 'LAINNYA'

**Comment by Sahrun** [comment]
Sudah
