### ISSUE TITLE
Form input data penduduk

### ISSUE THREAD

**Issue by lulus2019** [Sahrun/SID#37]
tambahkan form inputan untuk data kependudukan dan data lainnya yg menggunakan master data kependudukan..

- KTP Elektronik (Dropdown, enum)('Belum','Sudah')
- Nomor Akta Kelahiran (Input, varchar)
- Status Kewarganegaraan (Dropdown, enum)('WNI','WNA','Dua Kewarganegaraan')
- Nomor Paspor (input, varchar)
- Nomor KITAS/KITAP (input, varchar)
- Nama Ayah (input, varchar)(kecuali data kelahiran)
- Nama Ibu (input, varchar)(kecuali data kelahiran)

**Comment by lulus2019** [comment]
![form penduduk](https://user-images.githubusercontent.com/59117200/72069180-32efd980-3319-11ea-8d91-1a837cad0f84.png)

nama field ning tabel penduduk

**Comment by lulus2019** [comment]
ktp_elektronik | Enum
no_akta_kelahiran | Varchar(20)
status_warganegara | Enum
no_paspor | Varchar(20)
no_kitas_kitap | Varchar(20)
nama_ayah | Varchar(50)
nama_ibu | Varchar(50)

**Comment by Sahrun** [comment]
Silahkan di cek
