### ISSUE TITLE
Detail Penduduk (no KK)

### ISSUE THREAD

**Issue by lulus2019** [Sahrun/SID#39]
jika penduduk sudah masuk dalam kk maka no kk yg ditampilkan adalah nomor kk dr tabel keluarga, tapi kalau blm masuk dalam kk yg ditampilkan no kk di dlm tabel penduduk

**Comment by lulus2019** [comment]
update revisi..
hilangkan inputan no kk di penduduk, no kk hanya ada di data keluarga, tapi ketika menampilkan detail penduduk, yg ditampilkan no kk adalah dari data keluarga

**Comment by Sahrun** [comment]
Sudah Clear
